name = "stringsort"
author = "Jacob Williams"
maintainer = "Jacob Williams"
copyright = "Copyright (c) 2016-2021, Jacob Williams"
license = "BSD-3"
description = "Just some sorting routines for strings"
homepage = "https://github.com/jacobwilliams/stringsort"

[library]
source-dir = "src"

[install]
library = true

[build]
auto-executables = false
auto-examples = false
auto-tests = false

[[test]]
name = "test_natural"
source-dir = "tests"
main = "test_natural.f90"

[[test]]
name = "test"
source-dir = "tests"
main = "test.f90"
